name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  tests:
    runs-on: [self-hosted]
    env:
      PROJECT_PATH: ".\\"
    steps:
      - uses: actions/checkout@v2
      - name: Run EditMode Test
        run: Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-runTests -batchmode -testPlatform EditMode -projectPath $env:PROJECT_PATH  -testResults ./results-editmode.xml"
      - name: Run PlayMode Test
        run: Start-Process -Wait 'C:\Program Files\Unity\Hub\Editor\2020.3.12f1\Editor\Unity.exe' -ArgumentList "-runTests -batchmode -testPlatform PlayMode -projectPath $env:PROJECT_PATH  -testResults ./results-playmode.xml"
      - uses: actions/upload-artifact@v2
        with:
          name: results
          path: results*.xml
  build:
    runs-on: [self-hosted]
    env:
        PROJECT_PATH: ".\\"
        BUILD_METHOD_WIN64: "BuildProject.BuildWindows64"
        BUILD_METHOD_WIN32: "BuildProject.BuildWindows32"
        gameName: "Plataformote"
        projectVersion: "Test"
    steps:
      - uses: actions/checkout@v2
      - name: Build For Windows 64 bits
        run: Start-Process -Wait 'C:\Program Files\Unity\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN64 -quit"
      - name: Build For Windows 32 bits
        run: Start-Process -Wait 'C:\Program Files\Unity\Editor\Unity.exe' -ArgumentList "-nographics -batchmode -projectPath $env:PROJECT_PATH -executeMethod $env:BUILD_METHOD_WIN32 -quit"
      - uses: actions/upload-artifact@v2
        with:
          name: executable
          path: build/*